// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-uG-mQWBps4PVoBeWevkPE2m7IWwfbQ',
    appId: '1:1045548957686:web:3ec1017864a1e75705d1d7',
    messagingSenderId: '1045548957686',
    projectId: 'infiniqoute-b3200',
    authDomain: 'infiniqoute-b3200.firebaseapp.com',
    storageBucket: 'infiniqoute-b3200.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn3c2z1IRYn_Fs7B3JUxph5_n9UfrEa0g',
    appId: '1:1045548957686:android:e756ec93aa150a7505d1d7',
    messagingSenderId: '1045548957686',
    projectId: 'infiniqoute-b3200',
    storageBucket: 'infiniqoute-b3200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksL_Zqg89HYb0_nXrPaQxrAYGeCgNLIQ',
    appId: '1:1045548957686:ios:0b227f7d093b5dd105d1d7',
    messagingSenderId: '1045548957686',
    projectId: 'infiniqoute-b3200',
    storageBucket: 'infiniqoute-b3200.firebasestorage.app',
    iosBundleId: 'com.infiniquote.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksL_Zqg89HYb0_nXrPaQxrAYGeCgNLIQ',
    appId: '1:1045548957686:ios:0b227f7d093b5dd105d1d7',
    messagingSenderId: '1045548957686',
    projectId: 'infiniqoute-b3200',
    storageBucket: 'infiniqoute-b3200.firebasestorage.app',
    iosBundleId: 'com.infiniquote.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH-uG-mQWBps4PVoBeWevkPE2m7IWwfbQ',
    appId: '1:1045548957686:web:bacb01525b006e4f05d1d7',
    messagingSenderId: '1045548957686',
    projectId: 'infiniqoute-b3200',
    authDomain: 'infiniqoute-b3200.firebaseapp.com',
    storageBucket: 'infiniqoute-b3200.firebasestorage.app',
  );
}
