// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7t78tNsp5fUxlLMYySKwTvZrV3eOe78',
    appId: '1:670651887856:web:4cdc2a7dbf80ef3cef9235',
    messagingSenderId: '670651887856',
    projectId: 'radu-77c94',
    authDomain: 'radu-77c94.firebaseapp.com',
    storageBucket: 'radu-77c94.firebasestorage.app',
    measurementId: 'G-9SPJ6M3KG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVsqt-5BMB1p3-0pEz-2--faFbrvkG5Q',
    appId: '1:670651887856:android:40bfa8c6c644c5cfef9235',
    messagingSenderId: '670651887856',
    projectId: 'radu-77c94',
    storageBucket: 'radu-77c94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuC4m_IF_JBpHx-3gIVMspbJ2t96oa3rg',
    appId: '1:670651887856:ios:1077959c70024faeef9235',
    messagingSenderId: '670651887856',
    projectId: 'radu-77c94',
    storageBucket: 'radu-77c94.firebasestorage.app',
    iosBundleId: 'com.example.timeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuC4m_IF_JBpHx-3gIVMspbJ2t96oa3rg',
    appId: '1:670651887856:ios:1077959c70024faeef9235',
    messagingSenderId: '670651887856',
    projectId: 'radu-77c94',
    storageBucket: 'radu-77c94.firebasestorage.app',
    iosBundleId: 'com.example.timeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY7t78tNsp5fUxlLMYySKwTvZrV3eOe78',
    appId: '1:670651887856:web:3dacaa11de9064e4ef9235',
    messagingSenderId: '670651887856',
    projectId: 'radu-77c94',
    authDomain: 'radu-77c94.firebaseapp.com',
    storageBucket: 'radu-77c94.firebasestorage.app',
    measurementId: 'G-X0NZV3Q69J',
  );

}