// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2geqdPj_FHGpXY_b788Mle4tErdfBhy0',
    appId: '1:830774705235:web:e203437a3ddd357ee91aa6',
    messagingSenderId: '830774705235',
    projectId: 'timeverse-f53ff',
    authDomain: 'timeverse-f53ff.firebaseapp.com',
    storageBucket: 'timeverse-f53ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEV21ojpirDypuJ2mrXrKM3CfnWjucH4',
    appId: '1:830774705235:android:6e253106ae0c785ae91aa6',
    messagingSenderId: '830774705235',
    projectId: 'timeverse-f53ff',
    storageBucket: 'timeverse-f53ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9obX5tqgyvRiEPPC4mjm9ER168JF1po',
    appId: '1:830774705235:ios:02b31248d6fd8b6de91aa6',
    messagingSenderId: '830774705235',
    projectId: 'timeverse-f53ff',
    storageBucket: 'timeverse-f53ff.firebasestorage.app',
    iosBundleId: 'com.example.timeVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9obX5tqgyvRiEPPC4mjm9ER168JF1po',
    appId: '1:830774705235:ios:02b31248d6fd8b6de91aa6',
    messagingSenderId: '830774705235',
    projectId: 'timeverse-f53ff',
    storageBucket: 'timeverse-f53ff.firebasestorage.app',
    iosBundleId: 'com.example.timeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2geqdPj_FHGpXY_b788Mle4tErdfBhy0',
    appId: '1:830774705235:web:63ac7f6341559bcfe91aa6',
    messagingSenderId: '830774705235',
    projectId: 'timeverse-f53ff',
    authDomain: 'timeverse-f53ff.firebaseapp.com',
    storageBucket: 'timeverse-f53ff.firebasestorage.app',
  );

}